-- Which customer had the highest order volume in the month of October 2023?

SELECT CUSTOMER_ID, NAME, COUNT(ORDER_ID) AS ORDER_COUNT
FROM HOME_ASSIGNMENT.PUBLIC.TRANSFORMED_SALES_DATA
LEFT JOIN HOME_ASSIGNMENT.PUBLIC.RAW_CUSTOMER_DATA
ON CUSTOMER_ID = ID
WHERE YEAR = 2023 AND MONTH = 10
GROUP BY CUSTOMER_ID, NAME
ORDER BY ORDER_COUNT DESC
LIMIT 1;

-- OUTPUT
-- CUSTOMER_ID	NAME	        ORDER_COUNT
-- 2027	        g8f5j8VUxl	    2