-- What are the top 5 products by total sales amount in the year 2023?

WITH RANKED_PRODUCTS AS (
    SELECT
        PRODUCT_ID,
        SUM(TOTAL_SALES_AMOUNT) AS TOTAL_SALES,
        ROW_NUMBER() OVER (ORDER BY SUM(TOTAL_SALES_AMOUNT) DESC) AS ROW_NUM  -- ASSIGN ROW NUMBERS BASED ON TOTAL SALES -- HIGHEST SALES NUMBERED 1,2,3 ETC.
    FROM HOME_ASSIGNMENT.PUBLIC.TRANSFORMED_SALES_DATA
    WHERE YEAR = 2023  -- FILTER FOR THE YEAR 2023
    GROUP BY PRODUCT_ID
)

SELECT PRODUCT_ID, TOTAL_SALES
FROM RANKED_PRODUCTS
WHERE ROW_NUM <= 5;  -- SELECT ONLY THE TOP 5 PRODUCTS BASED ON THEIR RANK

-- OUTPUT
-- PRODUCT_ID	TOTAL_SALES
-- 3001	        4935.1
-- 3003	        3808.4
-- 3002	        3044.74
-- 3004	        2994.59
-- 3008	        2959.8